const sampleGoals = [
  {slug:'morning-pages',title:'Morning pages',description:'Write 3 pages #morning #writing',safebuf:0,doneToday:false,updated:6},
  {slug:'inbox-zero',title:'Inbox zero',description:'Reply to work messages #admin #quick',safebuf:1,doneToday:false,updated:42},
  {slug:'german',title:'Practice German',description:'20 sentences from a book #learning #deep',safebuf:1,doneToday:true,updated:20},
  {slug:'strength',title:'Strength training',description:'Complete today’s workout #health #gym',safebuf:2,doneToday:false,updated:180},
  {slug:'connection',title:'Reach out',description:'Make one request to connect #social #quick',safebuf:4,doneToday:false,updated:320},
  {slug:'read',title:'Read a book',description:'Read 20 focused pages #learning #deep',safebuf:6,doneToday:false,updated:90}
];
const $ = s => document.querySelector(s);
const state = {goals:[],query:'',hideDone:true,sort:'urgency',activeView:'all',views:JSON.parse(localStorage.getItem('bee-views')||'[]')};
const els={list:$('#goal-list'),empty:$('#empty-state'),search:$('#search-input'),clear:$('#clear-search'),doneFilter:$('#done-filter'),sort:$('#sort-select'),chips:$('#view-chips'),saveDialog:$('#save-dialog'),settingsDialog:$('#settings-dialog'),toast:$('#toast')};
function loadLocalGoals(){const stored=localStorage.getItem('bee-goals');state.goals=stored?JSON.parse(stored):sampleGoals.map(g=>({...g}));render()}
function urgency(goal){return goal.safebuf<=0?{color:'#ef5b4c',label:'Due today'}:goal.safebuf<=1?{color:'#ec8f2d',label:`Safe for ${goal.safebuf} day`}:goal.safebuf<=3?{color:'#d6a000',label:`Safe for ${goal.safebuf} days`}:{color:'#2eaa68',label:`Safe for ${goal.safebuf} days`}}
function tags(text){return [...text.matchAll(/#[\w-]+/g)].map(m=>m[0])}
function queryTokens(query){return query.match(/(?:[^\s"]+|"[^"]*")+/g)?.map(token=>token.replace(/^"|"$/g,'').toLowerCase())||[]}
function matchesQuery(goal){const haystack=`${goal.title} ${goal.description} ${goal.slug}`.toLowerCase();return queryTokens(state.query).every(token=>{const excluded=token.startsWith('-'),term=excluded?token.slice(1):token;const matched=term==='done:today'||term==='done'?goal.doneToday:haystack.includes(term);return excluded?!matched:matched})}
function filteredGoals(){let goals=state.goals.filter(g=>!state.hideDone||!g.doneToday).filter(matchesQuery);return goals.sort((a,b)=>state.sort==='name'?a.title.localeCompare(b.title):state.sort==='recent'?a.updated-b.updated:a.safebuf-b.safebuf)}
function addFilter(term){const tokens=queryTokens(state.query);if(!tokens.includes(term.toLowerCase()))tokens.push(term);state.query=tokens.join(' ');state.activeView='custom';render();els.search.focus()}
function render(){const goals=filteredGoals();els.list.innerHTML='';goals.forEach(goal=>{const node=$('#goal-template').content.firstElementChild.cloneNode(true),u=urgency(goal);node.style.setProperty('--urgency',u.color);node.classList.toggle('done',goal.doneToday);node.querySelector('.goal-icon').textContent=goal.title.slice(0,2);node.querySelector('h3').textContent=goal.title;node.querySelector('.description').textContent=goal.description;node.querySelector('.safety-pill').textContent=u.label;const tagWrap=node.querySelector('.tags');tags(goal.description).slice(0,3).forEach(t=>{const e=document.createElement('button');e.type='button';e.className='tag';e.textContent=t;e.setAttribute('aria-label',`Filter by ${t}`);e.onclick=()=>addFilter(t);tagWrap.append(e)});node.querySelector('.done-button').onclick=()=>toggleDone(goal.slug);els.list.append(node)});els.empty.hidden=goals.length>0;els.doneFilter.setAttribute('aria-pressed',state.hideDone);els.search.value=state.query;els.clear.hidden=!state.query;renderViews()}
function renderViews(){els.chips.innerHTML='';[{name:'All',query:'',hideDone:true,id:'all'},...state.views].forEach(v=>{const b=document.createElement('button');b.className='view-chip'+(v.id===state.activeView?' active':'');b.textContent=v.name;b.onclick=()=>{state.activeView=v.id;state.query=v.query;state.hideDone=v.hideDone;render()};if(v.id!=='all')b.ondblclick=()=>removeView(v.id);els.chips.append(b)})}
function toggleDone(slug){const g=state.goals.find(x=>x.slug===slug);g.doneToday=!g.doneToday;localStorage.setItem('bee-goals',JSON.stringify(state.goals));render();toast(g.doneToday?'Marked done today':'Moved back to focus')}
function removeView(id){state.views=state.views.filter(v=>v.id!==id);localStorage.setItem('bee-views',JSON.stringify(state.views));state.activeView='all';render();toast('View removed')}
function toast(msg){const e=els.toast;e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
els.search.oninput=e=>{state.query=e.target.value;state.activeView='custom';render()};els.clear.onclick=()=>{state.query='';state.activeView='all';render()};els.doneFilter.onclick=()=>{state.hideDone=!state.hideDone;state.activeView='custom';render()};els.sort.onchange=e=>{state.sort=e.target.value;render()};$('#reset-filters').onclick=()=>{state.query='';state.hideDone=false;render()};$('#settings-button').onclick=()=>{ $('#username').value=localStorage.getItem('bee-user')||'';$('#auth-token').value=localStorage.getItem('bee-token')||'';els.settingsDialog.showModal()};$('#save-view-button').onclick=()=>els.saveDialog.showModal();
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>addFilter(button.dataset.filter));
$('#save-view-form').onsubmit=e=>{if(e.submitter.value==='cancel')return;const name=$('#view-name').value.trim();if(!name)return;e.preventDefault();const v={id:Date.now().toString(),name,query:state.query,hideDone:state.hideDone};state.views.push(v);state.activeView=v.id;localStorage.setItem('bee-views',JSON.stringify(state.views));els.saveDialog.close();$('#view-name').value='';render();toast('View saved')};
$('#settings-form').onsubmit=async e=>{if(e.submitter.value==='cancel')return;e.preventDefault();const user=$('#username').value.trim(),token=$('#auth-token').value.trim();if(!user||!token){toast('Enter username and token');return}localStorage.setItem('bee-user',user);localStorage.setItem('bee-token',token);$('#connect-button').textContent='Connecting…';try{const url=`https://www.beeminder.com/api/v1/users/${encodeURIComponent(user)}/goals.json?auth_token=${encodeURIComponent(token)}&datapoints_count=1`;const res=await fetch(url);if(!res.ok)throw new Error('Could not connect');const data=await res.json();state.goals=data.map(g=>({slug:g.slug,title:g.title||g.slug,description:g.goaldate?`${g.fineprint||''} ${g.goaldate}`:g.fineprint||g.limsum||'',safebuf:Number.isFinite(g.safebuf)?g.safebuf:99,doneToday:Array.isArray(g.datapoints)&&g.datapoints.some(p=>new Date(p.timestamp*1000).toDateString()===new Date().toDateString()),updated:Date.now()/60000-(g.updated_at||0)/60}));localStorage.setItem('bee-goals',JSON.stringify(state.goals));$('#updated-label').textContent='Updated just now';els.settingsDialog.close();render();toast('Goals refreshed')}catch(err){toast(err.message)}finally{$('#connect-button').textContent='Connect & refresh'}};
$('#sample-button').onclick=()=>{localStorage.removeItem('bee-user');localStorage.removeItem('bee-token');state.goals=sampleGoals.map(g=>({...g}));localStorage.setItem('bee-goals',JSON.stringify(state.goals));$('#updated-label').textContent='Sample data';els.settingsDialog.close();render();toast('Showing sample goals')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
loadLocalGoals();
