const $=s=>document.querySelector(s),C=BeeCommitments,LOCAL=location.hostname==='localhost'||location.hostname==='127.0.0.1';
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
const state={config:C.newConfig(),logs:JSON.parse(localStorage.getItem('bee-commit-logs')||'{}'),goal:null,goals:[],editing:null,sync:'saved'};
const sample={slug:'daily-commitments',title:'Daily commitments',datapoints:[]};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function credentials(){return{user:localStorage.getItem('bee-user'),token:localStorage.getItem('bee-token'),slug:localStorage.getItem('bee-commit-goal')}}
function connected(){const x=credentials();return Boolean(x.user&&x.token&&x.slug)||LOCAL}
function daystamp(date=new Date()){return `${date.getFullYear()}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}`}
function logFor(date=daystamp()){return state.logs[date]||(state.logs[date]={})}
function persist(){localStorage.setItem('bee-commit-config',JSON.stringify(state.config));localStorage.setItem('bee-commit-logs',JSON.stringify(state.logs))}
function dueToday(){const now=new Date();return state.config.commitments.filter(item=>C.isDue(item,now))}
function deadlinePassed(item){return C.effectiveState({},item,new Date())==='missed'}
function randomSecret(){const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return [...bytes].map(v=>v.toString(36).padStart(2,'0')).join('').slice(0,32)}
function render(){const ok=connected();$('#setup').hidden=ok;$('#today').hidden=!ok;if(!ok)return;const date=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date());$('#date-label').textContent=date.toUpperCase();const due=dueToday(),log=logFor();const summary=C.aggregate(state.config,log,new Date());const logged=summary.counts.completed+summary.counts.snoozed+summary.counts.missed;$('#progress-value').textContent=`${logged}/${due.length}`;$('#commitment-list').innerHTML='';due.forEach(item=>$('#commitment-list').append(card(item,log,summary)));if(!due.length)$('#commitment-list').innerHTML='<div class="encouragement"><b>Nothing due today</b><span>Add a commitment or enjoy the clear day.</span></div>';$('#encouragement-title').textContent=logged===due.length&&due.length?'Today is fully logged.':'Show up for today.';$('#encouragement-copy').textContent=summary.strictFailure?'A strict commitment was missed. Today will sync as a failure.':`${due.length-logged} commitment${due.length-logged===1?'':'s'} still need an honest check-in.`;const all=Object.values(state.logs).flatMap(Object.values);$('#completed-stat').textContent=all.filter(x=>x==='completed').length;$('#snoozed-stat').textContent=all.filter(x=>x==='snoozed').length;$('#missed-stat').textContent=all.filter(x=>x==='missed').length;renderSync()}
function card(item,log,summary){const el=document.createElement('article');el.className='commitment';const current=summary.states.find(x=>x.item.id===item.id)?.state||'unlogged';el.innerHTML=`<div class="commitment-head"><div><h3></h3><span class="meta">Due ${formatTime(item.deadline)} · ${scheduleLabel(item.days)}</span></div><div>${item.strict?'<span class="strict-badge">STRICT</span>':''}<button class="edit" aria-label="Edit commitment">•••</button></div></div><div class="states"><button data-state="completed">✓ Completed</button><button data-state="snoozed">↷ Snooze</button><button data-state="missed">× Missed</button></div>`;el.querySelector('h3').textContent=item.name;el.querySelector('.edit').onclick=()=>openCommitment(item);el.querySelectorAll('[data-state]').forEach(button=>{const value=button.dataset.state;button.classList.toggle('active',current===value);button.disabled=value==='snoozed'&&(item.strict||deadlinePassed(item));button.onclick=()=>{log[item.id]=current===value?'unlogged':value;persist();state.sync='pending';render()}});return el}
function formatTime(value){const[h,m]=value.split(':').map(Number);return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,h,m))}
function scheduleLabel(days){return days.length===7?'Every day':days.map(i=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i]).join(', ')}
function renderSync(){const box=$('#sync-banner');box.className=`sync-banner ${state.sync}`;$('#sync-copy').textContent=state.sync==='pending'?'Saved locally · Beeminder sync pending':state.sync==='failed'?'Could not reach Beeminder · your log is safe':'Saved on this device · synced with Beeminder';$('#retry-button').hidden=state.sync!=='failed'}
function openCommitment(item=null){state.editing=item;$('#commitment-dialog-title').textContent=item?'Edit commitment':'New commitment';$('#commitment-id').value=item?.id||'';$('#commitment-name').value=item?.name||'';$('#commitment-deadline').value=item?.deadline||'21:00';$('#commitment-strict').checked=Boolean(item?.strict);$('#disable-secret').value='';const locked=Boolean(item?.strict);$('#commitment-name').disabled=locked;$('#commitment-deadline').disabled=locked;$('#commitment-strict').disabled=locked;$('#strict-note').hidden=!locked;$('#secret-field').hidden=!locked;$('#delete-commitment').hidden=!item||locked;document.querySelectorAll('#days input').forEach(input=>{input.checked=(item?.days||[0,1,2,3,4,5,6]).includes(Number(input.value));input.disabled=locked});$('#commitment-dialog').showModal()}
async function saveMetadata(){if(LOCAL&&!credentials().token)return;const {user,token,slug}=credentials(),title=C.encode(state.config);if(title.length>255)throw new Error('This configuration exceeds Beeminder’s 255-character goal-title limit. Remove or shorten a commitment.');const body=new URLSearchParams({auth_token:token,title});const response=await fetch(`https://www.beeminder.com/api/v1/users/${encodeURIComponent(user)}/goals/${encodeURIComponent(slug)}.json`,{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error(`Could not save configuration (${response.status})`)}
async function syncDay(){const due=dueToday(),summary=C.aggregate(state.config,logFor(),new Date());if(summary.counts.unlogged&&summary.states.some(x=>x.state==='unlogged'))throw new Error('Log every due commitment before saving.');state.sync='pending';renderSync();persist();if(LOCAL&&!credentials().token){state.sync='saved';render();toast('Sample day saved');return}const {user,token,slug}=credentials(),date=daystamp();const body=new URLSearchParams({auth_token:token,value:String(summary.score),daystamp:date,requestid:C.requestId(date),comment:C.comment(date,summary)});try{const response=await fetch(`https://www.beeminder.com/api/v1/users/${encodeURIComponent(user)}/goals/${encodeURIComponent(slug)}/datapoints.json`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error(`Sync failed (${response.status})`);state.sync='saved';localStorage.setItem(`bee-synced-${date}`,'1');toast(summary.strictFailure?'Saved · strict miss made today a failure':'Today saved to Beeminder')}catch(error){state.sync='failed';localStorage.setItem('bee-pending-sync',date);toast(error.message)}renderSync()}
async function loadGoals(){const{user,token}=credentials();if(!user||!token)return;const response=await fetch(`https://www.beeminder.com/api/v1/users/${encodeURIComponent(user)}.json?auth_token=${encodeURIComponent(token)}&associations=true&datapoints_count=30`,{cache:'no-store'});if(!response.ok)throw new Error(`Could not load goals (${response.status})`);const data=await response.json();state.goals=data.goals||[];const select=$('#goal-select');select.innerHTML='<option value="">Choose one goal</option>';state.goals.forEach(goal=>select.add(new Option(goal.slug,goal.slug)));select.value=credentials().slug||'';const goal=state.goals.find(x=>x.slug===select.value);if(goal){state.goal=goal;const remote=C.decode(goal.title);if(remote)state.config=remote;persist()}}
function setupDays(){['S','M','T','W','T','F','S'].forEach((name,index)=>{const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${index}"><span>${name}</span>`;$('#days').append(label)})}
setupDays();$('#connect-button').onclick=$('#settings-button').onclick=async()=>{$('#username').value=credentials().user||'';$('#token').value=credentials().token||'';$('#settings-dialog').showModal();try{await loadGoals()}catch(error){toast(error.message)}};$('#add-button').onclick=()=>openCommitment();$('#save-day').onclick=()=>syncDay().catch(error=>toast(error.message));$('#retry-button').onclick=()=>syncDay().catch(error=>toast(error.message));
$('#settings-form').onsubmit=async event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();localStorage.setItem('bee-user',$('#username').value.trim());localStorage.setItem('bee-token',$('#token').value.trim());const picked=$('#goal-select').value;if(picked)localStorage.setItem('bee-commit-goal',picked);try{await loadGoals();if(!credentials().slug){toast('Choose the single goal to use');return}$('#settings-dialog').close();render()}catch(error){toast(error.message)}};
$('#goal-select').onchange=()=>localStorage.setItem('bee-commit-goal',$('#goal-select').value);
$('#commitment-form').onsubmit=async event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();const existing=state.editing;if(existing?.strict){if($('#disable-secret').value!==existing.unlockSecret){toast('The disable secret does not match');return}existing.strict=false;existing.unlockSecret='';persist();$('#commitment-dialog').close();render();toast('Strict Mode disabled. Edit the commitment again.');return}const selected=[...document.querySelectorAll('#days input:checked')].map(x=>Number(x.value));if(!selected.length){toast('Choose at least one day');return}const strict=$('#commitment-strict').checked;const item={id:existing?.id||`c${Date.now().toString(36)}`,name:$('#commitment-name').value.trim(),deadline:$('#commitment-deadline').value,days:selected,strict,unlockSecret:strict?(existing?.unlockSecret||randomSecret()):''};if(existing)Object.assign(existing,item);else state.config.commitments.push(item);persist();try{await saveMetadata();$('#commitment-dialog').close();render();toast(strict?`Strict enabled. Save this disable secret: ${item.unlockSecret}`:'Commitment saved')}catch(error){toast(error.message)}};
$('#delete-commitment').onclick=async()=>{if(!state.editing)return;state.config.commitments=state.config.commitments.filter(x=>x.id!==state.editing.id);persist();try{await saveMetadata();$('#commitment-dialog').close();render();toast('Commitment deleted')}catch(error){toast(error.message)}};
(async function init(){if(LOCAL&&!credentials().slug){state.goal=sample;state.config={version:1,commitments:[{id:'morning',name:'Morning walk',days:[0,1,2,3,4,5,6],deadline:'10:00',strict:true,unlockSecret:'sample-disable-secret'},{id:'read',name:'Read for 20 minutes',days:[0,1,2,3,4,5,6],deadline:'21:00',strict:false},{id:'stretch',name:'Evening stretch',days:[1,3,5],deadline:'20:30',strict:false}]};localStorage.setItem('bee-commit-goal',sample.slug)}else{const cached=JSON.parse(localStorage.getItem('bee-commit-config')||'null');if(cached)state.config=C.normalize(cached);try{await loadGoals()}catch{state.sync='failed'}}if(localStorage.getItem('bee-pending-sync'))state.sync='failed';render()})();
